'use client'

import type { Metadata } from "next";
import { SideBar, Typography } from "../_components";
import { Sintony, Poppins } from "next/font/google";

import Image from 'next/image'
import { FaBell } from "react-icons/fa";
import { MdArrowDropDown } from "react-icons/md";
import "../globals.css";
import { usePathname, useSearchParams } from "next/navigation";

const sintony = Sintony({ weight: ["400"], subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "600"], subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Eduva",
//   description: "Generated by create next app",
// };

interface TitlePathMappings {
  [key: string]: object;
}

interface TitleRoleMappings {
  [key: string]: object;
}

const titleRoleMappings: TitleRoleMappings = {
  // Map user's role with the correct title
  administrate_roles: {
    dean: "Administrative pages"
  },
  program_roles: {
    other: "Program pages"
  },
  specializedProject_roles: {
    student: "Specialized project enrollment",
    other: "Specialized project management",
  },
  capstoneProject_roles: {
    student: "Capstone project enrollment",
    other: "Capstone project management",
  },
  assessment_roles: {
    other: "Assessment pages"
  },
  evaluation_roles: {
    other: "Evaluation pages"
  }
}

const titlePathMappings: TitlePathMappings = {
  // Determine role-title sets with path and param
  '/administrate': {
    'any': titleRoleMappings['administrate_roles']
  },
  '/program': {
    'any': titleRoleMappings['program_roles']
  },
  '/project': {
    'specialized': titleRoleMappings['specializedProject_roles'],
    'capstone': titleRoleMappings['capstoneProject_roles'],
    'any': titleRoleMappings['incorrect_param']
  },
  '/assessment': {
    'any': titleRoleMappings['assessment_roles']
  },
  '/evaluation': {
    'any': titleRoleMappings['evaluation_roles']
  }
};

function getTitle(){
  let currentPath = usePathname();
  let searchParam = useSearchParams();
  let currParam = null;
  searchParam.forEach((value, key) => {
    currParam = value;
  });

  // Get title sets based on current path
  let pathRoles = titlePathMappings[currentPath];

  // Get title sets based on path's params
  let paramRoles: any;
  if (currParam){
    console.log("Current param:", currParam);
    if (currParam in pathRoles){
      paramRoles = pathRoles[currParam];
    }
    else if ('any' in pathRoles)
      paramRoles = pathRoles['any'];
    else return "Invalid parameter, to 404"
  }
  else{
    return "No param provided, to 404?"
  }
  console.log(paramRoles)

  // Determine title based on user's role
  if (userRole){
    var finalTitle = null;
    if (userRole in paramRoles){
      finalTitle = paramRoles[userRole];
    }
    else{
      if ('other' in paramRoles)
        finalTitle = paramRoles['other'];
    } 

    if (finalTitle) return finalTitle
    else return "No defined title for current role, redirect 404 ?"
  }
  else
    return "No role found, not logged in ?"
}

///////////// Test session data
let userFullName = "User Name";
let usermail = "username@hcmut.edu.vn";
let userRole = 'student';
let profileImgSrc = '/logoHCMUT.png'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sintony.className} ${poppins.className} flex`}>
        <div className="w-80 h-screen"><SideBar /></div>
        <div className="flex-1 h-screen overflow-hidden">
          <div className="flex items-center flex-auto h-20 pl-8 pr-14 pt-5 gap-4">
            <div className="flex-auto w-full">
              <Typography
                variant="h1"
                text={getTitle()}
                color="text-darkblue"
              />
            </div>
            <button className="w-fit flex-auto"><FaBell size={25} /></button>

            <div 
              className='flex gap-3 items-center w-fit h-14 flex-auto cursor-pointer'
              onClick={()=>{
                const profileModal = document.getElementById('topBar-profileModal');
                if (profileModal){
                  if (profileModal.style.opacity == '0'){
                    // profileModal.style.maxHeight = '25em';
                    profileModal.style.display = 'flex';
                    const fadeTimeout = setTimeout(function removeModal() {
                      profileModal.style.opacity = '1.0';
                      clearTimeout(fadeTimeout);
                    }, 10)
                    
                  }
                  else{
                    // profileModal.style.maxHeight = '0em';
                    profileModal.style.opacity = '0';
                    const fadeTimeout = setTimeout(function removeModal() {
                      profileModal.style.display = 'none';
                      clearTimeout(fadeTimeout);
                    }, 300)
                  }
                }
              }}
            >
              <div className='relative w-11 h-11 px-1 py-1 rounded-full overflow-hidden'>
                <Image
                  src={profileImgSrc}
                  fill={true}
                  sizes="2.75rem"
                  alt="User's profile picture"
                />
              </div>
              <div className="font-medium w-fit max-w-xs max-h-14 whitespace-nowrap overflow-hidden">
                {userFullName}
              </div>
              <MdArrowDropDown size={35} />
            </div>
                
            <div 
              className="flex-col absolute w-80 rounded-xl shadow-xl bg-white z-20 py-5 items-center gap-2 overflow-hidden transition-opacity ease-in-out duration-200 delay-100" 
              id="topBar-profileModal"
              style={{left:'auto', right:'3.5rem', top:'5em', maxHeight:'25em', opacity:'0', display:'flex'}}
            >
              <div className='relative w-20 h-20 px-1 py-1 rounded-full overflow-hidden'>
                <Image
                  src={profileImgSrc}
                  fill={true}
                  sizes="2.75rem"
                  alt="User's profile picture"
                />
              </div>
              <div className="font-medium text-lg text-center w-full px-20 overflow-hidden">
                {userFullName}
              </div>
              <div className="font-normal text-sm text-center w-full px-20 overflow-hidden">
                {usermail}
              </div>
              <button 
                className="bg-red text-white font-semibold rounded-lg border-solid border-2 px-10 py-2 mt-2 w-fit"
                onClick={()=>alert("Logout")}
              >
                Logout
              </button>
            </div>

          </div>

          <div className="grow max-h-screen px-8 pb-20 overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
