import type { Metadata } from "next";
import { SideBar, Typography } from "../_components";
import { Sintony, Poppins } from "next/font/google";
import { FaBell } from "react-icons/fa";
import "../globals.css";

const sintony = Sintony({ weight: ["400"], subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "500", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eduva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sintony.className} ${poppins.className} flex`}>
        <div className="w-80 h-screen"><SideBar /></div>
        <div className="flex-1 h-screen overflow-hidden">
          <div className="flex items-center flex-auto h-20 pl-8 pr-14 pt-5 gap-4">
            <div className="flex-auto w-full">
              <Typography
                variant="h1"
                text={`Project Enrollment`}
                color="text-darkblue"
              />
            </div>
            <button className="w-fit-content flex-auto"><FaBell size={25}/></button>
            <div className='w-14 h-14 bg-blue flex-auto'></div>
          </div>

          <div className="grow max-h-screen px-8 pb-20 overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
