export enum ProjectStatus {
  APPROVED = 'APPROVED',
  WAITING_FOR_DEPARTMENT_HEAD = 'WAITING_FOR_DEPARTMENT_HEAD',
  WAITING_FOR_PROGRAM_CHAIR = 'WAITING_FOR_PROGRAM_CHAIR',
  REJECTED = 'REJECTED',
}
